# Generated by Django 6.1 on 2026-10-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_maximum_price_service_minimum_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='services.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'keyword'), name='unique_keyword_per_service')],
            },
        ),
    ]
