# Generated by Django 6.1 on 2026-08-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='artisans', to='services.service'),
        ),
    ]
