# Generated by Django 6.1 on 2026-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0003_artisan_business_name_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
