# Generated by Django 6.1 on 2026-10-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_artisan_alter_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_reminders_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='finalization_method',
            field=models.CharField(blank=True, choices=[('CUSTOMER_CONFIRMED', 'Confirmed by customer'), ('AUTO', 'Auto-finalized'), ('ADMIN', 'Finalized by admin')], max_length=20, null=True),
        ),
    ]
