# Generated by Django 6.1 on 2026-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_confirmation_reminders_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
